# Generated by Django 3.1.6 on 2021-02-27 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omkar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extra_data',
            old_name='list',
            new_name='desc',
        ),
    ]
