# Generated by Django 3.1.6 on 2021-03-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omkar', '0002_auto_20210227_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra_data',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
