# Generated by Django 3.1.6 on 2021-05-18 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omkar', '0004_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects_data',
            name='pic',
        ),
    ]
