# Generated by Django 3.1.6 on 2021-05-18 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omkar', '0005_remove_projects_data_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog_name_of_post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
